insert into public.jobs (
  slug,
  title,
  department,
  location,
  work_mode,
  experience,
  salary_min,
  salary_max,
  description,
  responsibilities,
  requirements,
  skills,
  status
)
values
(
  'senior-react-developer',
  'Senior React Developer',
  'technical',
  'Chennai',
  'hybrid',
  'senior',
  800000,
  1400000,
  'Build advanced, high-performance interfaces using React and Next.js for enterprise products.',
  array['Build UI systems', 'Improve performance', 'Mentor teammates'],
  array['3+ years React', 'Strong TypeScript', 'Next.js experience'],
  array['React', 'Next.js', 'TypeScript', 'Tailwind'],
  'active'
),
(
  'backend-node-developer',
  'Backend Node Developer',
  'technical',
  'Remote',
  'remote',
  'mid',
  700000,
  1200000,
  'Design reliable APIs, data models, and backend services.',
  array['Build APIs', 'Model data', 'Improve reliability'],
  array['2+ years Node.js', 'SQL fundamentals', 'API design'],
  array['Node.js', 'PostgreSQL', 'Redis'],
  'active'
),
(
  'product-designer-ui-ux',
  'Product Designer (UI/UX)',
  'technical',
  'Bengaluru',
  'hybrid',
  'mid',
  600000,
  1000000,
  'Create intuitive product journeys and scalable design systems.',
  array['Design flows', 'Prototype', 'Collaborate with engineering'],
  array['Portfolio', 'Design systems knowledge', 'User research basics'],
  array['Figma', 'Design Systems', 'Prototyping'],
  'active'
),
(
  'devops-engineer',
  'DevOps Engineer',
  'technical',
  'Remote',
  'remote',
  'senior',
  900000,
  1600000,
  'Own CI/CD, observability, and cloud reliability across products.',
  array['Manage pipelines', 'Improve reliability', 'Automate operations'],
  array['Cloud operations', 'CI/CD expertise', 'Monitoring tools'],
  array['AWS', 'Docker', 'Kubernetes', 'Terraform'],
  'active'
),
(
  'qa-automation-engineer',
  'QA Automation Engineer',
  'technical',
  'Chennai',
  'onsite',
  'junior',
  500000,
  800000,
  'Build automated testing pipelines for frontend and backend services.',
  array['Write test suites', 'Run regression plans', 'Report quality metrics'],
  array['Automation basics', 'Testing mindset', 'Scripting knowledge'],
  array['Playwright', 'Cypress', 'JavaScript'],
  'active'
),
(
  'performance-marketing-specialist',
  'Performance Marketing Specialist',
  'digital-marketing',
  'Remote',
  'remote',
  'mid',
  600000,
  1000000,
  'Run paid media campaigns and optimize attribution for growth.',
  array['Own paid channels', 'Analyze ROAS', 'Run experiments'],
  array['Paid media experience', 'GA4 proficiency', 'Analytical mindset'],
  array['Google Ads', 'Meta Ads', 'GA4'],
  'active'
),
(
  'seo-content-strategist',
  'SEO Content Strategist',
  'digital-marketing',
  'Bengaluru',
  'hybrid',
  'junior',
  500000,
  800000,
  'Drive organic growth via SEO and high-intent content.',
  array['Keyword strategy', 'Content planning', 'SERP analysis'],
  array['SEO fundamentals', 'Writing clarity', 'Analytics basics'],
  array['SEO', 'Search Console', 'Content Strategy'],
  'active'
),
(
  'social-media-manager',
  'Social Media Manager',
  'digital-marketing',
  'Chennai',
  'onsite',
  'fresher',
  240000,
  420000,
  'Manage social campaigns and daily community engagement.',
  array['Plan content', 'Track engagement', 'Coordinate creative assets'],
  array['Creative communication', 'Basic analytics', 'Execution discipline'],
  array['Social Strategy', 'Copywriting', 'Community Management'],
  'active'
),
(
  'email-marketing-specialist',
  'Email Marketing Specialist',
  'digital-marketing',
  'Remote',
  'hybrid',
  'mid',
  550000,
  900000,
  'Build lifecycle journeys and campaign automations to improve conversion.',
  array['Create campaign flows', 'Run segmentation', 'Track campaign metrics'],
  array['Email platform expertise', 'Copy testing', 'Data interpretation'],
  array['Resend', 'Lifecycle Marketing', 'Segmentation'],
  'active'
),
(
  'content-marketing-manager',
  'Content Marketing Manager',
  'digital-marketing',
  'Bengaluru',
  'hybrid',
  'senior',
  800000,
  1300000,
  'Own editorial direction and cross-channel content programs.',
  array['Lead editorial roadmap', 'Coach content team', 'Align content with revenue goals'],
  array['Leadership experience', 'Content strategy depth', 'Strong storytelling'],
  array['Editorial Strategy', 'SEO', 'Campaign Planning'],
  'active'
)
on conflict (slug) do nothing;
